-- MODULE
    insert into module(type) values ('Ressource Humaine'),
                                    ('Secretariat');

-- DIPLOME
    insert into diplome(type) values ('BEPC'),
                                    ('BACC'),
                                    ('LICENCE'),
                                    ('MASTER'),
                                    ('DOCTORAT');

-- NATIONALITE
    insert into Nationalite(type) values    ('Americain'),
                                            ('Bresilien'),
                                            ('Chilien'),
                                            ('Chinois'),
                                            ('Coreen'),
                                            ('Cubain'),
                                            ('Danois'),
                                            ('Espagnol'),
                                            ('Francais'),
                                            ('Grecque'),
                                            ('Hongrois'),
                                            ('Indien'),
                                            ('Italien'),
                                            ('Malagasy'),
                                            ('Mexicain'),
                                            ('Norvegien'),
                                            ('Portugais'),
                                            ('Quebecois'),
                                            ('Roumain'),
                                            ('Russe'),
                                            ('Suedois');

-- SITUATION MATRIMONIALE
    insert into Situation_Matrimoniale(type) values ('Celibataire'),
                                                    ('Fiance(e)'),
                                                    ('Marie(e)'),
                                                    ('Divorce(e)'),
                                                    ('Veuf(ve)');

-- REGION
    insert into Region(type) values ('Itasy'),
                                                    ('Analamanga'),
                                                    ('Vakinankaratra'),
                                                    ('Bongolava'),
                                                    ('Diana'),
                                                    ('Sava'),
                                                    ('Amoron i Mania'),
                                                    ('Haute Matsiatra'),
                                                    ('Vatovavy-Fitovinany'),
                                                    ('Atsimo-Atsinanana'),
                                                    ('Ihorombe'),
                                                    ('Sofia'),
                                                    ('Boeny'),
                                                    ('Bestiboka'),
                                                    ('Melaky'),
                                                    ('Alaotra-Mangoro'),
                                                    ('Atsinanana'),
                                                    ('Analanjirofo'),
                                                    ('Menabe'),
                                                    ('Atsimo-Andrefana'),
                                                    ('Androy'),
                                                    ('Anosy');

insert into Ville(idRegion,type) values    (1,'Ampefy'),
                                            (1,'Miarinarivo'),
                                            (1,'Arivonimamo'),
                                            (2,'Tananarivo'),
                                            (2,'Anjozorobe'),
                                            (2,'Talatamaty'),
                                            (2,'Ambohidratrimo'),
                                            (2,'Alasora'),
                                            (3,'Betafo'),
                                            (3,'Faratsiho'),
                                            (3,'Mandoto'),
                                            (3,'Ampitatafika'),
                                            (4,'Tsiroanomandidy'),
                                            (4,'Fenoarivo'),
                                            (4,'Ambatolampy'),
                                            (4,'Alaotra-Mangoro'),
                                            (5,'Atsiranana'),
                                            (5,'Ambilobe'),
                                            (5,'Antsalaka'),
                                            (6,'Sambava'),
                                            (6,'Marovato'),
                                            (7,'Ambositra'),
                                            (7,'Sandradahy');

insert into type_contrat(nom, acronyme) values  ('Le contrat de travail à durée indéterminée ','CDI'),
                                                ('Le contrat de chantier ou d opération ','CCO'),
                                                ('Le contrat à durée déterminée  ','CDD'),
                                                ('Le CDD à objet défini ','CDDO'),
                                                ('Le CDD senior ','CDDS'),
                                                ('Le contrat de travail temporaire ','CTT'),
                                                ('Le contrat de travail à temps partiel ','CTTP'),
                                                ('Le travail intermittent  ','TI'),
                                                ('Le contrat saisonnier  ','CS'),
                                                ('Le contrat vendanges  ','CV'),
                                                ('Le titre emploi-service entreprise','TESE');